[build]
  command = "npm --prefix frontend ci && npm --prefix frontend run build"
  publish = "frontend/build"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
